/** Local mock host only. Does not use Vendlists, AWS, eBay or real credentials. */
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
const html = await readFile(new URL('./dist/workbench.html', import.meta.url), 'utf8');
const camera = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 480 400"><rect width="480" height="400" fill="#edf0f5"/><ellipse cx="241" cy="326" rx="159" ry="18" fill="#d6dbe5"/><rect x="81" y="124" width="318" height="184" rx="23" fill="#242935"/><path d="M165 124l20-38h83l25 38" fill="#323846"/><rect x="106" y="141" width="56" height="28" rx="5" fill="#535b70"/><circle cx="256" cy="212" r="91" fill="#171e2c"/><circle cx="256" cy="212" r="74" fill="#46556f"/><circle cx="256" cy="212" r="59" fill="#1f293e"/><circle cx="256" cy="212" r="38" fill="#536b91"/><circle cx="240" cy="194" r="17" fill="#7e94b4"/><circle cx="373" cy="157" r="7" fill="#ce796b"/><path d="M102 186h44v102h-44z" fill="#31394a"/></svg>`;
const server = createServer((req, res) => {
 const url = new URL(req.url, 'http://127.0.0.1');
 res.setHeader('Cache-Control','no-store');
 if(url.pathname==='/widget') {res.setHeader('Content-Type','text/html');res.end(html);return;}
 if(url.pathname==='/camera.svg'){res.setHeader('Content-Type','image/svg+xml');res.end(camera);return;}
 if(url.pathname!=='/'){res.writeHead(404);res.end();return;}
 const theme = url.searchParams.get('theme')==='dark'?'dark':'light';
 const mode = ['empty','processing','failed','published','xss'].includes(url.searchParams.get('mode'))?url.searchParams.get('mode'):'draft';
 const state = { listingId:'demo-camera', updatedAt:'2026-10-03T18:00:00.000Z', title:mode==='xss'?'<img src=x onerror=alert(1)> camera':'Mirrorless digital camera with lens and original strap', status:mode==='draft'||mode==='xss'?'pending_review':mode, price:12999, currency:'GBP', marketplaceId:'EBAY_GB', quantity:1, conditionDescription:'Tested and working. Light marks on the body; see photos.', description:'Used camera with lens and original strap. Controls and lens have been tested. Small cosmetic marks are shown in the photos.', itemSpecifics:{Type:'Mirrorless camera',Colour:'Black','Included accessories':'Lens and original strap'}, imageUrls:[`http://127.0.0.1:${server.address().port}/camera.svg`], ebayAccountId:'demo-account', ...(mode==='published'?{ebayListingId:'demo-ebay-id'}:{}) };
 const script = `const frame=document.querySelector('iframe');let listing=${JSON.stringify(state)},sequence=0,agreed=false;const calls=[];const send=m=>frame.contentWindow.postMessage({jsonrpc:'2.0',...m},'*');const tool=data=>({content:[{type:'text',text:JSON.stringify(data)}],structuredContent:data});window.addEventListener('message',e=>{if(e.source!==frame.contentWindow)return;const m=e.data;if(m.method==='ui/initialize'){send({id:m.id,result:{protocolVersion:'2026-01-26',hostInfo:{name:'Local sample host',version:'0.1.0'},hostCapabilities:{serverTools:{},openLinks:{},message:{text:{}}},hostContext:{theme:${JSON.stringify(theme)},displayMode:'inline'}}});return;}if(m.method==='ui/notifications/initialized'){${mode==='empty'?'':"send({method:'ui/notifications/tool-result',params:tool({listing})});"}return;}if(m.method==='ui/notifications/size-changed'){frame.style.height=Math.min(2400,Math.max(300,m.params.height+8))+'px';return;}if(m.method==='tools/call'){const{name,arguments:a}=m.params;calls.push(name);document.getElementById('calls').textContent=calls.join(', ');let data;if(name==='vendlists_update_draft'){if(a.expectedUpdatedAt!==listing.updatedAt){send({id:m.id,result:{isError:true,content:[{type:'text',text:'This draft changed. Refresh and review the current values.'}]}});return;}listing={...listing,...a.changes,updatedAt:'2026-10-03T18:00:'+String(++sequence).padStart(2,'0')+'.000Z'};data={listing};}else if(name==='vendlists_quote_ebay_fees')data={quote:{state:'free',marketplaceId:'EBAY_GB',currency:'GBP',totalMinor:0},feeNotice:{confirmedSites:agreed?['EBAY_GB']:[]}};else if(name==='vendlists_acknowledge_ebay_fees'){agreed=true;data={feeNotice:{confirmedSites:['EBAY_GB']},published:false};}else if(name==='vendlists_publish'){listing={...listing,status:'published',ebayListingId:'demo-ebay-id'};data={success:true,ebayListingId:'demo-ebay-id'};}else if(name==='vendlists_generate'){listing={...listing,status:'processing'};data={status:'processing'};}else if(name==='vendlists_check_setup')data={observedAt:new Date().toISOString(),nextStep:'Confirm the selected account’s postage policy in the editor.'};else data={listing};send({id:m.id,result:tool(data)});return;}if(m.id!==undefined)send({id:m.id,result:{}});});`;
 res.setHeader('Content-Type','text/html');res.end(`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Vendlists workbench preview</title><style>body{margin:0;padding:22px;background:${theme==='dark'?'#161922':'#edf0f6'};font:14px system-ui;color:${theme==='dark'?'#eee':'#30384a'}}header{max-width:950px;margin:0 auto 15px}a{color:inherit;margin-right:12px}iframe{display:block;border:1px solid ${theme==='dark'?'#404756':'#dce2ed'};border-radius:16px;max-width:950px;width:100%;height:1000px;margin:auto;background:white}#calls{max-width:950px;margin:15px auto;overflow-wrap:anywhere;font-size:12px}</style></head><body><header><strong>Preview with sample data</strong><p>This is an isolated mock host. Actions do not affect any Vendlists or eBay account.</p><a href="/?theme=light">Light</a><a href="/?theme=dark">Dark</a><a href="/?mode=empty">Empty</a><a href="/?mode=processing">Processing</a><a href="/?mode=failed">Recovery</a><a href="/?mode=xss">Untrusted text</a></header><iframe title="Vendlists listing workbench" src="/widget"></iframe><p id="calls" aria-label="Mock tool calls">No tools called</p><script>${script}</script></body></html>`);
});
server.listen(43178,'127.0.0.1',()=>console.log('Sample-only workbench: http://127.0.0.1:43178'));
